server:
  port: 9002
#连接池
spring:
  application:
    name: bill-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bill-manager?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    #关闭thymeleaf缓存
  thymeleaf:
    cache: false

#整合mybatis
mybatis:
  type-aliases-package: com.yuhong.bill_service.entity  #别名搜索
  mapper-locations: classpath:/mybatis/*.xml

#注册实例时，更倾向于使用Ip地址，而不是host名
prefer-id-address: true
# ip地址
ip-address: 127.0.0.1
#续约间隔,默认30s
lease-renewal-interval-in-seconds: 5
#服务时效时间，默认90s
lease-expiration-duration-in-seconds: 5

#注册eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
